# NumPy and Pandas

<br>



<div style="display: flex; flex-wrap: wrap; align-items: center; gap: 15px; margin-bottom: 25px; padding-bottom: 15px; border-bottom: 1px solid #eaeaea;">
  
  <a href="https://colab.research.google.com/github/PatrickJHess/Volume-Three-Chapter-One/blob/master/colab/Colab_Numpy_And_Pandas.ipynb" target="_blank" style="display: flex; align-items: center;">
    <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab" style="height: 28px; margin: 0;">
  </a>
&emsp;
  <a href="https://mybinder.org/v2/gh/PatrickJHess/Volume-Three-Chapter-One/master?urlpath=lab/tree/notebooks/Numpy_And_Pandas.ipynb" target="_blank" style="background-color: #f5a252; color: white; padding: 0 12px; text-decoration: none; font-weight: bold; border-radius: 4px; font-family: sans-serif; display: flex; align-items: center; font-size: 0.9em; height: 28px; box-sizing: border-box;">
    <span style="margin-right: 6px; font-size: 1.1em;">🚀</span> Launch Live in Binder
  </a>
&emsp;
  <a href="https://patrickjhess.github.io/Volume-Three-Chapter-One/" style="background-color: #f1f3f4; color: #3c4043; border: 1px solid #dadce0; padding: 0 12px; text-decoration: none; font-weight: bold; border-radius: 4px; font-family: sans-serif; display: flex; align-items: center; font-size: 0.9em; height: 28px; box-sizing: border-box;">
    <span style="margin-right: 6px; font-size: 1.1em;">⬅️</span> Return to Main Book
  </a>

</div>

---

<details style="border: 1px solid #81d4fa; border-radius: 8px; padding: 15px; background-color: #e1f5fe; margin: 20px 0;">
  <summary style="cursor: pointer; font-weight: bold; font-size: 1.1em; color: #0277bd; font-family: sans-serif; list-style-position: inside;">
    <span style="margin-right: 8px;">💡</span> Important: How to use this page
  </summary>
  
  <div style="margin-top: 15px; padding-top: 15px; border-top: 1px solid #81d4fa; color: #01579b; font-family: sans-serif; font-size: 0.95em;">
    <ul style="line-height: 1.8; margin-bottom: 0;">
      <li><b>⏻ Run code right here:</b> Click the <b>Power Button</b> icon at the top of the screen to activate <b>Live Code</b>.</li>
      <li><b>📋 Copy code:</b> Hover over any code block and click the <b>Clipboard icon</b> in the top-right corner.</li>
      <li><b>📥 Download this file:</b> Click the <b>Download icon</b> (downward arrow) at the top right of the screen to save this exact notebook to your computer.</li>
    </ul>
  </div>
</details>

<details style="border: 1px solid #b8daff; border-radius: 8px; padding: 15px; background-color: #f8fbff; margin: 20px 0;">
  <summary style="cursor: pointer; font-weight: bold; font-size: 1.1em; color: #004085; font-family: sans-serif; list-style-position: inside;">
    <span style="margin-right: 8px;">🛠️</span> Notebook Setup: Why the "Try/Except" Imports?
  </summary>
  <div style="margin-top: 15px; padding-top: 15px; border-top: 1px solid #b8daff; color: #333333; font-family: sans-serif; font-size: 0.95em;">
    <b>The Goal:</b><br>
    To ensure this notebook runs perfectly whether you are using <b>Google Colab</b>, a local <b>Jupyter instance</b>, or a remote server without you having to manually install software.<br><br>
    <b>Key Concepts in this Section:</b>
    <ul style="line-height: 1.6; margin-bottom: 0;">
      <li><b>Standard Libraries:</b> Modules like <code>os</code>, <code>sys</code>, and <code>datetime</code> come "in the box" with Python. We use them for system tasks and date math.</li>
      <li><b>External Libraries:</b> NumPy and Pandas are the "heavy hitters" for data. They aren't always installed by default.</li>
      <li><b>The <code>try/except</code> Logic:</b> This is a safety net.
        <ol style="margin-top: 4px; margin-bottom: 4px; padding-left: 20px;">
          <li>We <b>try</b> to import the library.</li>
          <li>If it fails (because it's not installed), the <b>except</b> block triggers a <code>!pip install</code> to download it automatically.</li>
        </ol>
      </li>
      <li><b>Aliasing (<code>as np</code>):</b> We rename <code>numpy</code> to <code>np</code> to save keystrokes. In professional finance code, <code>np</code> and <code>pd</code> are the universal shorthand.</li>
    </ul>
  </div>
</details>

## Preparing the Notebook


### Importing libraries and functions

If the attempted import within the <font color='green'>try</font> segment fails, the <font color='green'>except</font> portion will install the libraries using <font color='green'>pip</font>, a package installer for Python. The exclamation mark preceding <font color='green'>pip</font> indicates that <font color='green'>pip</font> is running through the machine’s console rather than within the Notebook. Upon successful import, NumPy and Pandas are *aliased as* (or assigned the names of) <font color='green'>np</font> and <font color='green'>pd</font>, respectively (for more information on these statements, see [Control Statements](https://patrickjhess.github.io/Introduction-To-Python-For-Financial-Python/Control_Statements.html#the-try-and-except)).

```
try:
    import numpy as np
except:
    !pip install numpy
    import numpy as np
try:
    import pandas as pd
except:
    !pip install pandas
    import pandas as pd
```

In [ ]:
import os
try:
    import numpy as np
except:
    !pip install numpy
    import numpy as np
try:
    import pandas as pd
except:
    !pip install pandas
    import pandas as pd

<div style="display:block; border-left: 8px solid #2196f3; padding: 20px; background-color: #e3f2fd; border-radius: 0 8px 8px 0; margin: 20px 0; font-family: sans-serif;">
  <p style="margin-top: 0; color: #0d47a1; font-weight: bold; font-size: 1.1em;">💡 Quick Check: The "!" Prefix</p>
  <p style="color: #333333; margin-bottom: 15px; line-height: 1.6;"><strong>Question:</strong> In the code <code>!pip install numpy</code>, why is there an exclamation mark (<code>!</code>) before the command?</p>
  <details>
    <summary style="cursor: pointer; color: #1565c0; font-weight: bold; outline: none;">👉 Click here to reveal the answer</summary>
    <div style="margin-top: 12px; padding: 12px; border-left: 3px solid #2196f3; background-color: #ffffff; color: #333333; font-size: 0.95em; line-height: 1.6;">
      <strong>Answer:</strong> The <code>!</code> is a <strong>shell escape command</strong>. It tells the Jupyter Notebook: <em>"Stop running this as Python code for a second, and run it directly in the computer's terminal (command prompt) instead."</em> Since <code>pip</code> is an external program that manages your computer's files, Python itself doesn't "own" it—the operating system does.
    </div>
  </details>
</div>

<details style="border: 1px solid #81d4fa; border-radius: 8px; padding: 15px; background-color: #e1f5fe; margin: 20px 0;">
  <summary style="cursor: pointer; font-weight: bold; font-size: 1.1em; color: #0277bd; font-family: sans-serif; list-style-position: inside;">
    <span style="margin-right: 8px;">🔢</span> Important: Why NumPy for Fixed Income?
  </summary>
  <div style="margin-top: 15px; padding-top: 15px; border-top: 1px solid #81d4fa; color: #01579b; font-family: sans-serif; font-size: 0.95em; line-height: 1.6;">
    <b>The Mental Model:</b><br>
    Think of a NumPy <b>Array</b> as a high-powered version of a Python list. While standard Python lists are for general data, NumPy arrays are designed for <b>linear algebra and vector calculus</b>.<br><br>
    <b>What to look for in this section:</b>
    <ul style="margin-top: 8px; margin-bottom: 0; padding-left: 20px;">
      <li style="margin-bottom: 8px;"><b>Vectorization:</b> Notice how we apply a single formula (like <code>np.exp</code>) to an entire list of rates at once. In finance, this allows us to price 100 different bonds as easily as one.</li>
      <li style="margin-bottom: 8px;"><b>Dimensionality:</b> We will move from a 1D list of rates to a 2D "Matrix" that pairs rates with their corresponding Present Value factors.</li>
      <li style="margin-bottom: 0;"><b>Efficiency:</b> NumPy performs these calculations in C-extension memory, making it thousands of times faster than standard Python loops for large datasets.</li>
    </ul>
  </div>
</details>

## NumPy Arrays

The NumPy library offers efficient numerical procedures that simplify complex calculations(for more information see, [A Quick Introduction To NumPy](https://patrickjhess.github.io/Introduction-To-Python-For-Financial-Python/An_Introduction_To_NumPy.html#numpy)).The fundamental object in this library is the NumPy array. An array is simply a data structure in which elements are arranged and accessed. It can be formed from a single value or from an iterable data type like a list, which holds a series of values (see [A First Look at Lists](https://patrickjhess.github.io/Introduction-To-Python-For-Financial-Python/A_First_Look_At_Lists.html#a-first-look-at-lists)).NumPy must be imported before use; recall that in this Notebook, it was imported and aliased as <font color='green'>np</font> in the first code cell. The <font color='green'>array()</font> method is used to convert variables into NumPy arrays (**the allias np precedes the method array**) . The following code creates an array from the list <font color='green'>[3%, 5%, 7%]</font> (lists are stylized with square brackets) and assigns that array to <font color='green'>interest_rates</font>. This is then passed to <font color='green'>display()</font>, which simply displays the contents of <font color='green'>interest_rates</font>.

In [ ]:
interest_rates=np.array([0.03,0.05,0.07])
display(interest_rates)

array([0.03, 0.05, 0.07])

## NumPy Calculations

    
Now that we've created an array and assigned it to <font color='green'>interest_rates</font>, we can perform calculations on that array. NumPy calculates array elements individually. For instance, the <font color='green'>exp()</font> method used below raises Euler’s number, $e$, to the power of each element of <font color='green'>interest_rates</font> resulting in future value factors. This approach is faster and more convenient than iterating through the rates.

In [ ]:
display(np.exp(interest_rates))

array([1.03045453, 1.0512711 , 1.07250818])

<div style="display:block; border-left: 8px solid #28a745; padding: 20px; background-color: #f4fdf4; border-radius: 0 8px 8px 0; margin: 15px 0;">

### ✍️ Application: Create a NumPy Array

**The Challenge:** Create a new NumPy array containing the **present-value factors** calculated from the rates in `interest_rates`.

*Recall:* $PV = e^{-r*t}$. Use the vectorized power of NumPy to do this in a single line!

<hr style="border: 0; border-top: 1px solid #c3e6cb;">

<details>
<summary style="cursor: pointer; color: #155724; font-weight: bold;">💡 Stuck? Click for Hints & Resources</summary>
<div style="margin-top: 12px; padding: 10px; border-left: 3px solid #28a745; background-color: #ffffff;">

* **Hint:** Remember that NumPy can handle negative exponents and scalar multiplication across the whole array.
* **Documentation:** [Chapter One Hints ↗](https://patrickjhess.github.io/Hints-Results/Chapter_One_Hints.html#create-a-numpy-array)
* **Verification:** [Expected Results ↗](https://patrickjhess.github.io/Hints-Results/Chapter_One_Results.html#create-a-numpy-array)

</div>
</details>

</div>

## Two-Dimensional NumPy arrays

    
The <font color='green'>pv_rates</font> array in the code below is a *two-dimensional* NumPy array (or matrix). It's created by combining two one-dimensional arrays&mdash;<font color='green'>interest_rates</font> and <font color='green'>pv_factors</font>&mdash;within the <font color='green'>array()</font> method. To access the rows of this two-dimensional array, we'll use the corresponding row *index* value. (The index value is simply an element's sequential position in the array. Remember that in programming, sequences begin at position 0, not 1). Finally, both the interest rates and present-value factors are displayed below using *f-strings*. These are like strings, but begin with an "f" and are used to include variables and expressions within a string. The variable must be enclosed in curly brackets (i.e., { }), and the indexed value must be enclosed in square brackets ([ ]).

In [ ]:
#A calculation is make for each element of a numpy array
pv_factors=1/np.exp(interest_rates)
pv_rates=np.array([interest_rates,pv_factors])
display(pv_rates)
#Create an f string for each row.
#Each row must also be encapsulated in curly brackets
display(f'Interest Rates {pv_rates[0]}')
display(f'Present Value Factors {pv_rates[1]}')

array([[0.03      , 0.05      , 0.07      ],
       [0.97044553, 0.95122942, 0.93239382]])

'Interest Rates [0.03 0.05 0.07]'

'Present Value Factors [0.97044553 0.95122942 0.93239382]'

<div style="display:block; border-left: 8px solid #28a745; padding: 20px; background-color: #f8fff9; border-radius: 0 8px 8px 0; margin: 20px 0; box-shadow: 2px 2px 5px rgba(0,0,0,0.02);">

### ✍️ Application: Two-Dimensional Matrix Manipulation

**The Challenge:** Create a new two-dimensional array by performing a specialized calculation on your existing data.

1.  Take the **interest-rate row** from your matrix.
2.  Raise it to Euler’s number ($e^r$).
3.  Multiply the resulting values by the **present value factors**.

*Goal: This verifies the relationship between discount factors and compounding rates within a single NumPy object.*

<hr style="border: 0; border-top: 1px solid #d4edda; margin: 15px 0;">

<details>
<summary style="cursor: pointer; color: #155724; font-weight: bold;">💡 Need a Hint or Verification?</summary>
<div style="margin-top: 12px; padding: 15px; border-left: 3px solid #28a745; background-color: #ffffff; border-radius: 4px;">

* **Logic Hint:** Use `np.exp()` on the first row (index `0`) and multiply it by the second row (index `1`).
* **Detailed Guide:** [Chapter One Hints ↗](https://patrickjhess.github.io/Hints-Results/Chapter_One_Hints.html#manipulate-two-dimensional-array)
* **Final Answer:** [Expected Results ↗](https://patrickjhess.github.io/Hints-Results/Chapter_One_Results.html#manipulate-two-dimensional-array)

</div>
</details>

</div>

<details style="border: 1px solid #81d4fa; border-radius: 8px; padding: 15px; background-color: #e1f5fe; margin: 20px 0;">
  <summary style="cursor: pointer; font-weight: bold; font-size: 1.1em; color: #0277bd; font-family: sans-serif; list-style-position: inside;">
    <span style="margin-right: 8px;">🐼</span> Important: Why Pandas for Fixed Income?
  </summary>
  <div style="margin-top: 15px; padding-top: 15px; border-top: 1px solid #81d4fa; color: #01579b; font-family: sans-serif; font-size: 0.95em; line-height: 1.6;">
    <b>The Mental Model:</b><br>
    If NumPy is the "engine" that does the math, <b>Pandas</b> is the "dashboard" that makes the data readable. It turns raw matrices into labeled tables called <b>DataFrames</b>.<br><br>
    <b>Key Advantages:</b>
    <ul style="margin-top: 8px; margin-bottom: 0; padding-left: 20px;">
      <li style="margin-bottom: 8px;"><b>Labeling:</b> Instead of remembering that "Row 1 is the PV Factor," we can give columns names like <code>Interest_Rate</code> and <code>PV_Factor</code>.</li>
      <li style="margin-bottom: 8px;"><b>Data Alignment:</b> Pandas ensures that if you sort your rates, the corresponding PV factors stay perfectly aligned with them.</li>
      <li style="margin-bottom: 0;"><b>Readability:</b> DataFrames render as clean, professional HTML tables in your Jupyter Book, making them much easier for clients or researchers to audit.</li>
    </ul>
  </div>
</details>

## Creating a Pandas DataFrame from NumPy Arrays

### A simple example


    
The Pandas library is a powerful resource for data analysis. Recall that like NumPy, we imported Pandas in our earlier code cell. For this section, we'll be using Pandas to access a structure called a *DataFrame*. A Pandas DataFrame organizes data into rows and columns, much like an Excel spreadsheet or a NumPy array. It can be created from a two-dimensional array, such as our newly created <font color='green'>pv_rates</font>. The simplest DataFrames automatically assign row and column index values; a more functional approach allows for the explicit naming of both. In the simple example below, the <font color='green'>DataFrame()</font> method of Pandas uses three arrays as arguments, generating a row for each array.

In [ ]:
# Dataframe created with DataFrame() method
simple_example=pd.DataFrame((interest_rates,
              np.exp(interest_rates),
              1/np.exp(interest_rates)))
display(simple_example)

          0         1         2
0  0.030000  0.050000  0.070000
1  1.030455  1.051271  1.072508
2  0.970446  0.951229  0.932394

<div style="display:block; border-left: 8px solid #1f77b4; padding: 20px; background-color: #f0f7ff; border-radius: 0 8px 8px 0; margin: 20px 0;">

### 🐼 Application: Building a Pandas DataFrame

**The Challenge:** Convert your two-dimensional `pv_rates` array into a structured **Pandas DataFrame**.

* **Goal:** Transform the raw matrix into a labeled table that clearly identifies which values are interest rates and which are present-value factors.
* **Pro-Tip:** Remember that DataFrames often prefer data in columns. You may need to **Transpose** your array using `.T` during the creation process!

<hr style="border: 0; border-top: 1px solid #d1e3f3; margin: 15px 0;">

<details>
<summary style="cursor: pointer; color: #124d77; font-weight: bold;">💡 Click for DataFrame Hints & Resources</summary>
<div style="margin-top: 12px; padding: 15px; border-left: 3px solid #1f77b4; background-color: #ffffff; border-radius: 4px;">

* **Constructor Hint:** Use `pd.DataFrame(data, columns=['Name1', 'Name2'])`.
* **Documentation:** [Chapter One Hints ↗](https://patrickjhess.github.io/Hints-Results/Chapter_One_Hints.html#create-a-dataframe-from-a-two-dimensional-array)
* **Verification:** [Expected Results ↗](https://patrickjhess.github.io/Hints-Results/Chapter_One_Results.html#create-a-dataframe-from-a-two-dimensional-array)

</div>
</details>

</div>

## Making rows into columns and labeling the columns




In the below code, rows are converted to columns by using the <font color='green'>transpose()</font> method on our earlier DataFrame, <font color='green'>simple_example</font>. This method changes the rows into columns (see [A Quick Introduction To Pandas](https://patrickjhess.github.io/Introduction-To-Python-For-Financial-Python/An_Introduction_To_Pandas.html#the-transpose)). The transposed result is then assigned to <font color='green'>rows_to_columns</font>, and the columns are then assigned the elements of a list (<font color='green'>['Rates', 'Future Value', 'Present Value']</font>).  Transposing the DataFrame makes <font color='green'>'Rates'</font>, <font color='green'>'Future Value'</font>, and <font color='green'>'Present Value'</font> the variables and makes the rows the observations of those variables.

In [ ]:
#transpose the simple_example dataframe and call it rows_to_columns
rows_to_columns=simple_example.transpose()
#(the transpose method can also be written as simple_example.T)
rows_to_columns.columns=['Rates','Future Value','Present Value']
display(rows_to_columns)

   Rates  Future Value  Present Value
0   0.03      1.030455       0.970446
1   0.05      1.051271       0.951229
2   0.07      1.072508       0.932394

## The set_index() method


Once the DataFrame has been transposed, the next step is to make the <font color='green'>Rates</font> column the index.  Why? The reason is that the values of <font color='green'>Rates</font> determine the values of the columns <font color='green'>Future Value</font> and <font color='green'>Pesent Value</font>. This change isn't necessary, but it draws our eye to a natural connection. Instead of an index that points only to a row number, the new index points to the rate that results in the future and present values.

The method <font color='green'>set_index()</font> takes a column name and removes the column from the DataFrame ([an example](https://patrickjhess.github.io/Introduction-To-Python-For-Financial-Python/An_Introduction_To_Pandas.html#making-a-column-the-index)). Pandas has a built-in *fail-safe-switch*. By default, this change (and others we'll encounter later) doesn't permanently alter the DataFrame. This might seem a bit strange, but this characteristic prevents mistakes that are difficult to fix. To make the change permanent, you can do the following:


1.   Assign the transposed value of the DataFrame to another DataFrame
      *
      ```
      name_index_set_index=rows_to_columns.set_index('Rates')
      display(name_index_set)
      ```

2.   Change the default value of the <font color='green'>inplace</font> argument of <font color='green'>set_index</font>  to True
      *


      ```
      rows_to_columns.set_index('Rates',inplace=True)
      display(rows_to_columns)
      ```

In [ ]:
name_index_set_index=rows_to_columns.set_index('Rates')
display(name_index_set_index)
display(rows_to_columns)
rows_to_columns.set_index('Rates',inplace=True)
display(rows_to_columns)

<div style="display:block; border-left: 8px solid #2196f3; padding: 20px; background-color: #e3f2fd; border-radius: 0 8px 8px 0; margin: 20px 0; font-family: sans-serif;">
  <p style="margin-top: 0; color: #0d47a1; font-weight: bold; font-size: 1.1em;">📝 Check Your Understanding: NumPy & Pandas</p>
  <p style="color: #333333; margin-bottom: 5px;"><strong>Q1: The Power of Vectorization</strong><br>If <code>r = np.array([0.02, 0.04, 0.06])</code>, what is the result of <code>1 / (1 + r)</code>?</p>
  <ul style="margin-top: 0; margin-bottom: 15px; color: #333333; padding-left: 20px; line-height: 1.6;">
    <li><strong>A)</strong> An error.</li>
    <li><strong>B)</strong> A single value.</li>
    <li><strong>C)</strong> A new array containing $[0.980, 0.961, 0.943]$.</li>
  </ul>
  <p style="color: #333333; margin-bottom: 5px;"><strong>Q2: Indexing Challenge</strong><br>In a 2D NumPy array called <code>data</code>, what does <code>data[0, 2]</code> retrieve?</p>
  <ul style="margin-top: 0; margin-bottom: 15px; color: #333333; padding-left: 20px; line-height: 1.6;">
    <li><strong>A)</strong> The 1st row, 3rd column.</li>
    <li><strong>B)</strong> The 3rd row, 1st column.</li>
  </ul>
  <p style="color: #333333; margin-bottom: 5px;"><strong>Q3: Pandas Utility</strong><br>Why would you convert a NumPy array into a Pandas DataFrame?</p>
  <ul style="margin-top: 0; margin-bottom: 20px; color: #333333; padding-left: 20px; line-height: 1.6;">
    <li><strong>A)</strong> To make the math run faster.</li>
    <li><strong>B)</strong> To add headers and index labels for easier data manipulation.</li>
  </ul>
  <hr style="border: 0; border-top: 1px solid #90caf9; margin: 15px 0;">
  <details>
    <summary style="cursor: pointer; color: #1565c0; font-weight: bold; outline: none;">👉 Click here to reveal the answers</summary>
    <div style="margin-top: 12px; padding: 12px; border-left: 3px solid #2196f3; background-color: #ffffff; color: #333333; font-size: 0.95em; line-height: 1.6;">
      <strong>Answers:</strong>
      <ol style="margin-top: 8px; margin-bottom: 0; padding-left: 20px;">
        <li><strong>C</strong> (NumPy automatically applies the division to every element).</li>
        <li><strong>A</strong> (Python is 0-indexed; 0 is the first row, 2 is the third column).</li>
        <li><strong>B</strong> (NumPy is faster for math, but Pandas is superior for organization and labeling).</li>
      </ol>
    </div>
  </details>
</div>

<div style="display: flex; flex-wrap: wrap; align-items: center; gap: 15px; margin-bottom: 25px; padding-bottom: 15px; border-bottom: 1px solid #eaeaea;">
  
  <a href="https://colab.research.google.com/github/PatrickJHess/Volume-Three-Chapter-One/blob/master/colab/Colab_Numpy_And_Pandas.ipynb" target="_blank" style="display: flex; align-items: center;">
    <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab" style="height: 28px; margin: 0;">
  </a>
&emsp;
  <a href="https://mybinder.org/v2/gh/PatrickJHess/Volume-Three-Chapter-One/master?urlpath=lab/tree/notebooks/Numpy_And_Pandas.ipynb" target="_blank" style="background-color: #f5a252; color: white; padding: 0 12px; text-decoration: none; font-weight: bold; border-radius: 4px; font-family: sans-serif; display: flex; align-items: center; font-size: 0.9em; height: 28px; box-sizing: border-box;">
    <span style="margin-right: 6px; font-size: 1.1em;">🚀</span> Launch Live in Binder
  </a>
&emsp;
  <a href="https://patrickjhess.github.io/Volume-Three-Chapter-One/" style="background-color: #f1f3f4; color: #3c4043; border: 1px solid #dadce0; padding: 0 12px; text-decoration: none; font-weight: bold; border-radius: 4px; font-family: sans-serif; display: flex; align-items: center; font-size: 0.9em; height: 28px; box-sizing: border-box;">
    <span style="margin-right: 6px; font-size: 1.1em;">⬅️</span> Return to Main Book
  </a>

</div>

---